### PR TITLE
Validate inputs for ?ae7q and ?qrz commands

### LINKED ISSUE #345: ?ae7q and ?qrz should validate inputs
### Is your feature request related to a problem? Please describe.

The ?ae7q and ?qrz commands should validate inputs, since their inputs are being interpolated into URLs, and special characters could enable mischief.

### Describe the solution you'd like

Ensure only alphanumeric inputs are being passed into these commands.

### PR DESCRIPTION
**Pull request by franrogers**
### Description

I added input validation to the ?ae7q and ?qrz commands (callsigns, FRNs, and license IDs). This is very basic validation, just confirming that the input is alphanumeric/numeric, since it's getting passed into URLs.

Fixes #345

### Type of change

- New feature 

### How has this been tested?

Tested the commands using my own instance of the bot.

### Checklist

- [X] Issue exists for PR
- [X] Code reviewed by the author
- [X] Code documented (comments or other documentation)
- [X] Changes tested
- [X] All tests pass (see [`DEVELOPING.md`][0], if it exists)
- [ ] [`CHANGELOG.md`][1] updated if needed
- [X] Informative commit messages
- [X] Descriptive PR title

[0]: /DEVELOPING.md
[1]: /CHANGELOG.md

### CODE REVIEW

**Comment by classabbyamp** [comment]
As I commented on the issue, the code here will be massively reworked before the next release, so we should probably hold off on changing it for now.

Regarding the code you wrote, you can do this much more easily using [`.isalnum()`](https://docs.python.org/3/library/stdtypes.html#str.isalnum), e.g.:
```py
if not callsign.isalnum():
    ...
```
Otherwise, it looks good.

**Comment by franrogers** [comment]
My Perl-addled brain forgot `str.isalnum()` and friends existed. I've gone ahead and updated my changes to use that instead of `re`.

**Review by classabbyamp — APPROVED** [review]
On second thought, I think we'll merge this now as a temp fix.

**Review by 0x5c — APPROVED** [review]

**Comment by classabbyamp** [comment]
@franrogers not sure if you use GPG but we have had it set up so that commits need to be signed to be merged into `master`.

image

**Pull request merged**
